# Generated by Django 3.1.2 on 2020-10-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='numPAge',
            new_name='numPags',
        ),
    ]
