# Generated by Django 3.1.1 on 2020-10-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20201023_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idLibro',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
